LANGUAGES {AR0, SV0, HE0, DA0, CS0, ES1, CH1, HU0, GAE, FR0, FI0, CH0, IT0, PT0, EN0, DE0, KO0, PL0, US0, ES0, RU0, NL0, NO0}

ADVANCED_SEARCH:
  CHK "Additional services0123456789",
  CHK "Additional services",
  AR0 "Additional services",
  SV0 "Additional services",
  HE0 "Additional services",
  DA0 "Additional services",
  CS0 "Additional services",
  ES1 "Additional services",
  CH1 "Additional services",
  HU0 "Additional services",
  GAE "Additional services",
  FR0 "Additional services",
  FI0 "Additional services",
  CH0 "Additional services",
  IT0 "Additional services",
  PT0 "Additional services",
  EN0 "Additional services",
  DE0 "Additional services",
  KO0 "Additional services",
  PL0 "Additional services",
  US0 "Additional services",
  ES0 "Additional services",
  RU0 "Additional services",
  NL0 "Additional services",
  NO0 "Additional services";

ID_CARD:
  CHK "Directory card01234567",
  CHK "Directory card",
  AR0 "Directory card",
  SV0 "Directory card",
  HE0 "Directory card",
  DA0 "Directory card",
  CS0 "Directory card",
  ES1 "Directory card",
  CH1 "Directory card",
  HU0 "Directory card",
  GAE "Directory card",
  FR0 "Directory card",
  FI0 "Directory card",
  CH0 "Directory card",
  IT0 "Directory card",
  PT0 "Directory card",
  EN0 "Directory card",
  DE0 "Directory card",
  KO0 "Directory card",
  PL0 "Directory card",
  US0 "Directory card",
  ES0 "Directory card",
  RU0 "Directory card",
  NL0 "Directory card",
  NO0 "Directory card";

INSTANT_MESSAGE:
  CHK "instant message012345678",
  CHK "instant message",
  AR0 "instant message",
  SV0 "instant message",
  HE0 "instant message",
  DA0 "instant message",
  CS0 "instant message",
  ES1 "instant message",
  CH1 "instant message",
  HU0 "instant message",
  GAE "instant message",
  FR0 "instant message",
  FI0 "instant message",
  CH0 "instant message",
  IT0 "instant message",
  PT0 "instant message",
  EN0 "instant message",
  DE0 "instant message",
  KO0 "instant message",
  PL0 "instant message",
  US0 "instant message",
  ES0 "instant message",
  RU0 "instant message",
  NL0 "instant message",
  NO0 "instant message";

VOICE_CALL:
  CHK "Last communication0",
  CHK "Last communication",
  AR0 "Last communication",
  SV0 "Last communication",
  HE0 "Last communication",
  DA0 "Last communication",
  CS0 "Last communication",
  ES1 "Last communication",
  CH1 "Last communication",
  HU0 "Last communication",
  GAE "Last communication",
  FR0 "Last communication",
  FI0 "Last communication",
  CH0 "Last communication",
  IT0 "Last communication",
  PT0 "Last communication",
  EN0 "Last communication",
  DE0 "Last communication",
  KO0 "Last communication",
  PL0 "Last communication",
  US0 "Last communication",
  ES0 "Last communication",
  RU0 "Last communication",
  NL0 "Last communication",
  NO0 "Last communication";

C2C:
  CHK "Click to call012345678",
  CHK "Click to call",
  AR0 "Click to call",
  SV0 "Click to call",
  HE0 "Click to call",
  DA0 "Click to call",
  CS0 "Click to call",
  ES1 "Click to call",
  CH1 "Click to call",
  HU0 "Click to call",
  GAE "Click to call",
  FR0 "Click to call",
  FI0 "Click to call",
  CH0 "Click to call",
  IT0 "Click to call",
  PT0 "Click to call",
  EN0 "Click to call",
  DE0 "Click to call",
  KO0 "Click to call",
  PL0 "Click to call",
  US0 "Click to call",
  ES0 "Click to call",
  RU0 "Click to call",
  NL0 "Click to call",
  NO0 "Click to call";

NOTC2C:
  CHK "No phone is associated to this contact012345678",
  CHK "No phone is associated to this contact",
  AR0 "No phone is associated to this contact",
  SV0 "No phone is associated to this contact",
  HE0 "No phone is associated to this contact",
  DA0 "No phone is associated to this contact",
  CS0 "No phone is associated to this contact",
  ES1 "No phone is associated to this contact",
  CH1 "No phone is associated to this contact",
  HU0 "No phone is associated to this contact",
  GAE "No phone is associated to this contact",
  FR0 "No phone is associated to this contact",
  FI0 "No phone is associated to this contact",
  CH0 "No phone is associated to this contact",
  IT0 "No phone is associated to this contact",
  PT0 "No phone is associated to this contact",
  EN0 "No phone is associated to this contact",
  DE0 "No phone is associated to this contact",
  KO0 "No phone is associated to this contact",
  PL0 "No phone is associated to this contact",
  US0 "No phone is associated to this contact",
  ES0 "No phone is associated to this contact",
  RU0 "No phone is associated to this contact",
  NL0 "No phone is associated to this contact",
  NO0 "No phone is associated to this contact";

INTRO_DATE:
  CHK "the012345678",
  CHK "the",
  AR0 "the",
  SV0 "the",
  HE0 "the",
  DA0 "the",
  CS0 "the",
  ES1 "the",
  CH1 "the",
  HU0 "the",
  GAE "the",
  FR0 "the",
  FI0 "the",
  CH0 "the",
  IT0 "the",
  PT0 "the",
  EN0 "the",
  DE0 "the",
  KO0 "the",
  PL0 "the",
  US0 "the",
  ES0 "the",
  RU0 "the",
  NL0 "the",
  NO0 "the";

VIDEO_CALL:
  CHK "video call012345678",
  CHK "video call",
  AR0 "video call",
  SV0 "video call",
  HE0 "video call",
  DA0 "video call",
  CS0 "video call",
  ES1 "video call",
  CH1 "video call",
  HU0 "video call",
  GAE "video call",
  FR0 "video call",
  FI0 "video call",
  CH0 "video call",
  IT0 "video call",
  PT0 "video call",
  EN0 "video call",
  DE0 "video call",
  KO0 "video call",
  PL0 "video call",
  US0 "video call",
  ES0 "video call",
  RU0 "video call",
  NL0 "video call",
  NO0 "video call";

LAST_ACCESS:
  CHK "Last access01234567",
  CHK "Last access",
  AR0 "Last access",
  SV0 "Last access",
  HE0 "Last access",
  DA0 "Last access",
  CS0 "Last access",
  ES1 "Last access",
  CH1 "Last access",
  HU0 "Last access",
  GAE "Last access",
  FR0 "Last access",
  FI0 "Last access",
  CH0 "Last access",
  IT0 "Last access",
  PT0 "Last access",
  EN0 "Last access",
  DE0 "Last access",
  KO0 "Last access",
  PL0 "Last access",
  US0 "Last access",
  ES0 "Last access",
  RU0 "Last access",
  NL0 "Last access",
  NO0 "Last access"