// Generated by CoffeeScript 1.6.2
(function() {
  define(['formvalidate', 'i18n!nls/login'], function($, i18n) {
    $("span#version").html(window.param.version);
    $("span#buildNumber").html(window.param.buildNumber);
    $.formValidator.initConfig({
      formID: "loginForm",
      autoTip: true
    }, {
      onError: function(msg) {}
    }, {
      inIframe: false
    });
    $("#idLoginname").formValidator({
      onShow: "",
      onFocus: "",
      onCorrect: ""
    }).inputValidator({
      min: 1,
      max: 30,
      onError: i18n.nameerrtip
    });
    $("#idPassword").formValidator({
      onShow: "",
      onFocus: "",
      onCorrect: ""
    }).inputValidator({
      min: 1,
      max: 30,
      onError: i18n.pwderrtip
    });
    return $('#loginForm').on('submit', function() {
      if ($.formValidator.pageIsValid()) {
        return $("#idSubmit").attr('disabled', true).css('color', 'grey');
      }
    });
  });

}).call(this);
