// Generated by CoffeeScript 1.5.0
(function() {

  define(function(require) {
    var init, ready;
    init = function() {
      return typeof console !== "undefined" && console !== null ? console.debug("transmng panel init...") : void 0;
    };
    return ready = function() {
      return typeof console !== "undefined" && console !== null ? console.debug("transmng panel ready...") : void 0;
    };
  });

}).call(this);
