// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require) {
    var $, charsetgrid, languagegrid, util;
    $ = require('jqgrid');
    require('jqlayout');
    util = require('util');
    charsetgrid = require('admin/charsetgrid');
    languagegrid = require('admin/languagegrid');
    $('#adminTabs').tabs({
      show: function(event, ui) {
        var pheight, pwidth;
        pheight = $(ui.panel).height();
        pwidth = $(ui.panel).width();
        if (typeof console !== "undefined" && console !== null) {
          console.debug("height=" + pheight + ", width=" + pwidth + ".");
        }
        return $('table.ui-jqgrid-btable', ui.panel).setGridHeight(pheight - 90).setGridWidth(pwidth - 20);
      }
    });
    $('#loading-container').fadeOut('slow', function() {
      return $(this).remove();
    });
    return util.afterInitilized(this);
  });

}).call(this);
