// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require) {
    var $, charsetgrid, languagegrid, util;
    $ = require('jqgrid');
    require('jqlayout');
    util = require('util');
    charsetgrid = require('admin/charsetgrid');
    languagegrid = require('admin/languagegrid');
    $('#adminTabs').tabs({
      activate: function(event, ui) {
        return typeof console !== "undefined" && console !== null ? console.log(ui) : void 0;
      },
      load: function(event, ui) {
        return typeof console !== "undefined" && console !== null ? console.log(ui) : void 0;
      },
      create: function(event, ui) {
        return typeof console !== "undefined" && console !== null ? console.log(ui) : void 0;
      },
      heightStyle: "fill"
    });
    $('#loading-container').fadeOut('slow', function() {
      return $(this).remove();
    });
    return util.afterInitilized(this);
  });

}).call(this);
