// Generated by CoffeeScript 1.7.1

/*
  Obtain given dictName action ids in dictionaryGridList grid
 */

(function() {
  var getDictActionIds;

  getDictActionIds = function(dictName) {
    var actionStr, atag, dictRow, dictRows, langId, strId, _ref;
    dictRows = (function() {
      var _i, _len, _ref, _results;
      _ref = $('#dictionaryGridList').getRowData();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        dictRow = _ref[_i];
        if (dictRow.name === dictName) {
          _results.push(dictRow);
        }
      }
      return _results;
    })();
    if (!dictRows.length) {
      return {};
    }
    actionStr = dictRows[0].action;
    _ref = (function() {
      var _i, _len, _ref, _results;
      _ref = actionStr.split(/(?:&nbsp;)+/);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        atag = _ref[_i];
        _results.push($(atag).attr('id'));
      }
      return _results;
    })(), strId = _ref[0], langId = _ref[1];
    return {
      strId: strId,
      langId: langId
    };
  };

}).call(this);
