define [

], (

)->

  203: 'EXCEED_MAX_LENGTH'
  208: 'DUPLICATE_LABEL_REFERENCE'
  401: 'PARAMETERS_INCORRECT'
  402: 'BR_NUMBER_INCONSISTENT'
  204: 'MALFORMED_CHARACTER_ENCODING'
  205: 'SUSPICIOUS_CHARACTER_ENCODING'
  333: 'Test'
