// Generated by CoffeeScript 1.4.0
(function() {

  define(['jqlayout', 'taskmng/task_grid', 'i18n!nls/common', 'taskmng/dialogs', 'util', 'require'], function($, grid, c18n, dialogs, util, require) {
    var gridParent, taskFileUpload;
    require('jqueryui');
    $('#productBase').change(function() {
      $('#productRelease').empty();
      if (parseInt($('#productBase').val()) === -1) {
        return false;
      }
      return $.getJSON("rest/products/version", {
        base: $(this).val(),
        prop: 'id,version'
      }, function(json) {
        return $('#productRelease').append(util.newOption(c18n.select.release.tip, -1)).append(util.json2Options(json)).trigger('change');
      });
    });
    $('#productRelease').change(function() {
      var param;
      param = {
        release: {
          id: $(this).val(),
          version: $(this).find("option:selected").text()
        }
      };
      if (!param.release.id || parseInt(param.release.id) === -1) {
        return false;
      }
      return grid.productVersionChanged(param);
    });
    if (!param.currentSelected.productId || '-1' === String(param.currentSelected.productId)) {
      $('#productRelease option:last').attr('selected', true);
    }
    $('#productRelease').trigger('change');
    $("#progressbar").draggable({
      grid: [50, 20],
      opacity: 0.35
    }).progressbar({
      create: function(e, ui) {
        this.label = $('.progressbar-label', this);
        return $(this).position({
          my: 'center',
          at: 'center',
          of: window
        });
      },
      change: function(e, ui) {
        return this.label.html(($(this).progressbar("value").toPrecision(4)) + "%");
      }
    }).hide();
    taskFileUpload = 'taskFileUpload';
    $('#uploadTask').button({
      label: 'Upload'
    }).css({
      overflow: 'hidden'
    }).append($("<input type='file' id='" + taskFileUpload + "' name='upload' title='Choose file' multiple/>").css({
      position: 'absolute',
      top: 0,
      right: 0,
      margin: 0,
      border: '1px transparent',
      borderWidth: '0 0 40px 0px',
      opacity: 0,
      filter: 'alpha(opacity=0)',
      cursor: 'pointer'
    }));
    $('#loading-container').fadeOut('slow', 'swing', function() {
      return $(this).remove();
    });
    util.afterInitilized(this);
    $('#optional-container').show();
    gridParent = $('.taskGrid_parent');
    return $('#taskGrid').setGridWidth(gridParent.width() - 10).setGridHeight(gridParent.height() - 60);
  });

}).call(this);
