// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require) {
    var init, onShow, ready;
    onShow = function() {};
    init = function() {
      return typeof console !== "undefined" && console !== null ? console.debug("transmng panel init...") : void 0;
    };
    ready = function() {
      return typeof console !== "undefined" && console !== null ? console.debug("transmng panel ready...") : void 0;
    };
    return {
      onShow: onShow
    };
  });

}).call(this);
