// Generated by CoffeeScript 1.3.3
(function() {

  define(['jqgrid', 'util', 'require'], function($, util, require) {
    var transDetailGrid;
    transDetailGrid = $("#viewDetailGrid").jqGrid({
      url: 'json/transdetailgrid.json',
      mtype: 'POST',
      postData: {},
      editurl: "",
      datatype: 'json',
      width: $(window).width() * 0.6,
      height: 200,
      shrinkToFit: false,
      rownumbers: true,
      loadonce: false,
      pager: '#ViewDetailPager',
      rowNum: 60,
      rowList: [10, 20, 30, 60, 120],
      sortname: 'key',
      sortorder: 'asc',
      viewrecords: true,
      gridview: true,
      multiselect: true,
      cellEdit: true,
      cellurl: 'http://127.0.0.1:2000',
      colNames: ['Label', 'Max len', 'Context', 'Reference language', 'Translation'],
      colModel: [
        {
          name: 'label',
          index: 'label',
          width: 100,
          editable: false,
          stype: 'select',
          align: 'left',
          frozen: true
        }, {
          name: 'maxlen',
          index: 'maxlen',
          width: 90,
          editable: true,
          align: 'right',
          frozen: true,
          search: false
        }, {
          name: 'context',
          index: 'context',
          width: 80,
          align: 'left',
          frozen: true,
          search: false
        }, {
          name: 'reflang',
          index: 'reflang',
          width: 150,
          align: 'left',
          frozen: true,
          search: false
        }, {
          name: 'trans',
          index: 'trans',
          width: 250,
          align: 'left',
          frozen: true,
          search: false
        }
      ],
      afterCreate: function(grid) {
        return grid.navGrid('#ViewDetailPager', {
          edit: false,
          add: false,
          del: false,
          search: false,
          view: false
        });
      }
    });
    return transDetailGrid.getGridParam('afterCreate')(transDetailGrid);
  });

}).call(this);
