// Generated by CoffeeScript 1.6.2
(function() {
  $(function($) {
    var browserData, color, colors, data, entry, idx, json, msg, subEntry, subIdx, versionsData, _i, _j, _len, _len1, _ref;

    colors = Highcharts.getOptions().colors;
    msg = "{\n\"dictNum\": 5,\n\"labelNum\": 247,\n\"translationNum\": 5435,\n\"translationWC\": 34141,\n\n\"distinctTranslationNum\": 4503,\n\"distinctTranslationWC\": 30813,\n\n\"untranslatedNum\": 299,\n\"untranslatedWC\": 1301,\n\"translatedNum\": 4204,\n\"translatedWC\": 29512,\n\n\"matchedNum\": 391,\n\"matchedWC\": 2656\n}";
    json = $.parseJSON(msg);
    data = [
      {
        name: 'Distinct',
        y: json.distinctTranslationNum,
        drilldown: [
          {
            name: 'Translated',
            y: json.untranslatedNum
          }, {
            name: 'Untranslated',
            y: json.translatedNum
          }
        ]
      }, {
        name: 'Duplicated',
        y: json.translationNum - json.distinctTranslationNum,
        drilldown: [
          {
            name: 'Duplicated',
            y: json.translationNum - json.distinctTranslationNum
          }
        ]
      }
    ];
    browserData = [];
    versionsData = [];
    for (idx = _i = 0, _len = data.length; _i < _len; idx = ++_i) {
      entry = data[idx];
      browserData.push({
        name: "" + entry.name + " translations",
        y: entry.y,
        color: colors[idx]
      });
      _ref = entry.drilldown;
      for (subIdx = _j = 0, _len1 = _ref.length; _j < _len1; subIdx = ++_j) {
        subEntry = _ref[subIdx];
        color = Highcharts.Color(colors[idx]).brighten(0.2 - subIdx / entry.drilldown.length / 10).get();
        versionsData.push({
          name: "" + subEntry.name + " translations",
          y: subEntry.y,
          color: color
        });
      }
    }
    return $('#container').highcharts({
      chart: {
        type: 'pie'
      },
      title: {
        text: 'Browser market share, April, 2011'
      },
      yAxis: {
        title: {
          text: 'Total percent market share'
        }
      },
      plotOptions: {
        pie: {
          shadow: false,
          center: ['50%', '50%']
        }
      },
      series: [
        {
          name: 'Total translations',
          data: browserData,
          size: '60%',
          dataLabels: {
            formatter: function() {
              return "" + this.point.name + ": " + this.point.y + "(" + (this.point.percentage.toFixed(2)) + "%)";
            },
            color: 'white',
            distance: -30
          }
        }, {
          name: 'Distict translations',
          data: versionsData,
          size: '80%',
          innerSize: '60%',
          dataLabels: {
            formatter: function() {
              return "" + this.point.name + ": " + this.point.y + "(" + (this.point.percentage.toFixed(2)) + "%)";
            }
          }
        }
      ]
    });
  });

}).call(this);
