// Generated by CoffeeScript 1.6.2
(function() {
  define({
    root: {
      langgrid: {
        caption: 'Language List'
      },
      charsetgrid: {
        caption: 'Charset List'
      }
    },
    "zh-cn": true
  });

}).call(this);
