// Generated by CoffeeScript 1.5.0
(function() {

  define({
    root: {
      loadingpage: '<h1><img src="busy.gif" />Loading page please wait...</h1>',
      all: 'All',
      dictformats: 'DCT:DCT;Dictionary conf:Dictionary conf;Text properties:Text properties;XML labels:XML labels;XML properties:XML properties;XMLDict:XMLDict;VLEExcel:VLEExcel',
      dictencodings: 'ISO-8859-1:ISO-8859-1;UTF-8:UTF-8;UTF-16LE:UTF-16LE;UTF-16BE:UTF-16BE',
      "import": 'Import',
      ok: 'OK',
      cancel: 'Cancel',
      "export": 'Export',
      "yes": 'Yes',
      no: 'No',
      close: 'Close',
      error: 'Error',
      warning: 'Warning',
      confirm: 'Confirm',
      message: 'Message',
      create: 'Create',
      prod: 'product',
      app: 'application',
      dict: 'dictionary',
      language: 'language',
      selrow: 'Please select {0} first',
      'selecttip': 'Please select',
      select: {
        product: {
          tip: 'Please select product',
          msg: 'Please select product',
          msgtitle: 'Select product'
        },
        release: {
          tip: 'Please select product release',
          msg: 'Please select product release!',
          msgtitle: 'Select product release'
        }
      }
    },
    "zh-cn": true
  });

}).call(this);
