// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    var PanelGroup, layout, pg, tDialog, tTabs;
    PanelGroup = (function() {

      function PanelGroup(panels, currentPanel) {
        this.panels = panels;
        this.currentPanel = currentPanel;
      }

      PanelGroup.prototype.switchTo = function(panelId, callback) {
        $("" + this.panels).hide();
        this.currentPanel = panelId;
        if (typeof console !== "undefined" && console !== null) {
          console.debug("switch to " + this.panels + "[id='" + panelId + "'].");
        }
        return $("" + this.panels + "[id='" + panelId + "']").fadeIn("fast", function() {
          if ($.isFunction(callback)) {
            return callback();
          }
        });
      };

      return PanelGroup;

    })();
    tDialog = $('#testDialog').dialog({
      autoOpen: false,
      title: 'Test Dialog.',
      buttons: [
        {
          text: 'Test',
          click: function(e) {
            return alert('OK');
          }
        }, {
          text: 'Close',
          click: function(e) {
            return $(this).dialog('close');
          }
        }
      ]
    });
    tTabs = $('#p2 > .testTabs').tabs({
      show: function(event, ui) {
        return typeof console !== "undefined" && console !== null ? console.log(ui) : void 0;
      },
      show: function(event, ui) {
        return typeof console !== "undefined" && console !== null ? console.log("width: " + ($(ui.panel).width()) + ", height: " + ($(ui.panel).height()) + ".") : void 0;
      }
    });
    pg = new PanelGroup('div.panel', 'p1');
    pg.switchTo('p2', function() {});
    $('#switchPanel').button().click(function(e) {
      if (pg.currentPanel === 'p1') {
        tDialog.dialog('close');
        return pg.switchTo('p2', function() {
          var height;
          return height = $("#" + pg.currentPanel).height();
        });
      } else {
        pg.switchTo('p1');
        return tDialog.dialog('open');
      }
    });
    return layout = $('#layout-container').layout({
      applyDefaultStyles: true
    });
  });

}).call(this);
