// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require) {
    var layout, ready;
    require('jqlayout');
    ready = function(param) {
      return typeof console !== "undefined" && console !== null ? console.debug("global layout ready...") : void 0;
    };
    layout = $('#global-container').layout({
      defaults: {
        size: 'auto'
      },
      north: {
        minSize: 34,
        togglerLength_closed: -1,
        resizable: false
      }
    });
    ready();
    return {
      layout: layout
    };
  });

}).call(this);
