// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require) {
    var $, appmngPanel, glayout, init, ready, util;
    $ = require('jqgrid');
    util = require('dms-util');
    glayout = require('globallayout');
    appmngPanel = require('appmng/main');
    ready = function(param) {
      if (typeof console !== "undefined" && console !== null) {
        console.debug("page ready...");
      }
      glayout.layout.resizeAll();
      return $('#loading-container').fadeOut('slow', function() {
        return $(this).remove();
      });
    };
    init = function() {
      var currentBtn, dmsPanels;
      dmsPanels = new util.PanelGroup('div.dms-panel', 'appmng.jsp');
      $('span.navigator-button').button().click(function() {
        var currentPanel;
        currentPanel = "" + ($(this).attr('value'));
        $('span.page-title').text($("#pageNavigator>option[value='" + currentPanel + "']").text());
        $("span[id^='nav']").removeClass('navigator-button-currentpage');
        $("span[id^='nav'][value='" + currentPanel + "']").addClass('navigator-button-currentpage');
        $("span[id^='nav'] > span.ui-button-text > span").removeClass('navigator-tab-title-currentpage');
        $("span[id^='nav'][value='" + currentPanel + "'] > span.ui-button-text > span").addClass('navigator-tab-title-currentpage');
        return dmsPanels.switchTo(currentPanel);
      }).parent().buttonset();
      currentBtn = $("span[id^='nav'][value='appmng.jsp']");
      currentBtn.addClass('navigator-button-currentpage');
      $("span.ui-button-text > span", currentBtn).addClass('navigator-tab-title-currentpage');
      return dmsPanels.switchTo('appmng.jsp');
    };
    init();
    return ready();
  });

}).call(this);
