// Generated by CoffeeScript 1.5.0
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(['require', 'jqtree', 'jqmsgbox', 'dms-util', 'dms-urls', 'i18n!nls/common'], function(require, $, msgbox, util, urls, c18n) {
    var appTree, getNodeInfo, nodeCtxMenu, removeNode, timeFunName, _ref, _ref1, _ref2, _ref3;
    appTree = null;
    getNodeInfo = util.getProductTreeInfo;
    removeNode = function(node) {
      return $.post(urls[node.attr('type')].del, {
        id: node.attr('id')
      }, function(json) {
        if (json.status !== 0) {
          $.msgBox(json.message, null, {
            title: c18n.error,
            width: 300,
            height: 'auto'
          });
          return false;
        }
        return appTree != null ? appTree.remove(node) : void 0;
      });
    };
    nodeCtxMenu = {
      products: {
        createproduct: {
          label: 'New product',
          "_disabled": (_ref = util.urlname2Action(urls.product.create), __indexOf.call(param.forbiddenPrivileges, _ref) >= 0),
          action: function(node) {
            return appTree != null ? appTree.create(node, 'last', {
              data: 'NewProduct',
              attr: {
                type: 'product',
                id: null
              }
            }, (function() {}), false) : void 0;
          },
          separator_before: true
        }
      },
      product: {
        createapp: {
          label: 'New application',
          "_disabled": (_ref1 = util.urlname2Action(urls.app.create), __indexOf.call(param.forbiddenPrivileges, _ref1) >= 0),
          action: function(node) {
            return appTree != null ? appTree.create(node, 'last', {
              data: 'NewApp',
              attr: {
                type: 'app',
                id: null
              }
            }, (function() {}), false) : void 0;
          }
        },
        del: {
          label: 'Delete product',
          "_disabled": (_ref2 = util.urlname2Action(urls.product.del), __indexOf.call(param.forbiddenPrivileges, _ref2) >= 0),
          action: removeNode,
          separator_before: true
        }
      },
      app: {
        del: {
          label: 'Delete application',
          "_disabled": (_ref3 = util.urlname2Action(urls.app.del), __indexOf.call(param.forbiddenPrivileges, _ref3) >= 0),
          action: removeNode
        }
      }
    };
    $.jstree._themes = "css/jstree/themes/";
    timeFunName = null;
    $.getJSON(urls.navigateTree, {}, function(treeInfo) {
      return $("#appTree").jstree({
        json_data: {
          data: treeInfo
        },
        ui: {
          select_limit: 1
        },
        themes: {},
        core: {
          initially_open: ["-1"]
        },
        contextmenu: {
          items: function(node) {
            return nodeCtxMenu[node.attr('type')];
          }
        },
        plugins: ["themes", "json_data", "ui", "core", "crrm", "contextmenu"]
      }).bind('create.jstree', function(event, data) {
        var name, node, pbId;
        appTree = data.inst;
        node = data.rslt.obj;
        name = data.rslt.name;
        if ('' === name) {
          $.jstree.rollback(data.rlbk);
          return;
        }
        if ('app' === node.attr('type')) {
          pbId = appTree._get_parent(node).attr('id');
        }
        return $.post(urls[node.attr('type')].create, {
          name: name,
          prod: pbId
        }, function(json) {
          if (json.status !== 0) {
            $.msgBox(json.message, null, {
              title: c18n.error,
              width: 300,
              height: 'auto'
            });
            $.jstree.rollback(data.rlbk);
            return false;
          }
          return data.rslt.obj.attr({
            id: json.id
          });
        });
      }).bind('loaded.jstree', function(event, data) {
        appTree = data.inst;
        if (window.param.currentSelected.productBaseId) {
          return appTree.select_node($("#appTree li [id=" + param.currentSelected.productBaseId + "][type=product]"));
        }
      }).bind("select_node.jstree", function(event, data) {
        clearTimeout(timeFunName);
        return timeFunName = setTimeout(function() {
          var currentModule, currentTab, module, node, nodeInfo;
          appTree = data.inst;
          node = data.rslt.obj;
          nodeInfo = getNodeInfo(node);
          currentTab = $("#pageNavigator").val();
          currentModule = currentTab.split('.')[0];
          module = require("" + currentModule + "/main");
          return module != null ? typeof module.nodeSelect === "function" ? module.nodeSelect(node, nodeInfo) : void 0 : void 0;
        }, 300);
      }).bind('dblclick_node.jstree', function(event, data) {
        clearTimeout(timeFunName);
        return data.inst.toggle_node(data.rslt.obj);
      });
    });
    return {
      getNodeInfo: getNodeInfo
    };
  });

}).call(this);
