// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  define(['jqueryui', 'jqupload'], function($, fileupload) {
    var d;
    d = $('#hiDialog').dialog({
      autoOpen: false,
      buttons: [
        {
          text: 'OK',
          click: function(e) {
            return typeof console !== "undefined" && console !== null ? console.log(fileupload) : void 0;
          }
        }
      ]
    });
    return $("#showDialog").button().on('click', function(e) {
      return d.dialog("open");
    });
  });

}).call(this);

//# sourceMappingURL=testrequirejs.js.map
