// Generated by CoffeeScript 1.4.0
(function() {

  define({
    root: {
      langgrid: {
        caption: 'Language List',
        'dummy': ''
      },
      charsetgrid: {
        caption: 'Charset List',
        'dummy': ''
      }
    },
    "zh-cn": true
  });

}).call(this);
