// Generated by CoffeeScript 1.4.0
(function() {

  define({
    root: {
      select: {
        product: '选择产品',
        application: '选择应用',
        version: '选择版本'
      },
      grid: {
        delappmsg: 'Please select application to delete.',
        permanenttext: 'Delete permanently',
        dictlistpreview: {
          caption: 'Dictionaries in zip'
        }
      },
      dialog: {
        addapplication: {
          tip: 'There is no application to add.',
          'dummy': ''
        },
        stringsettings: {
          title: '字符串设置',
          'dummy': ''
        },
        languagesettings: {
          title: '语言设置',
          'dummy': ''
        },
        "delete": {
          title: '删除',
          "delmsg": 'Delete selected {0}(s)?'
        },
        dictlistpreview: {
          title: 'Dictionaries Preview',
          "import": 'Import',
          check: 'There are some errors need to be fixed before import!',
          success: 'Import dictionaries to {0} successful. <br/><br/>{1}'
        },
        dictpreviewstringsettings: {
          title: 'String settings',
          'dummy': ''
        },
        "addlanguage": {
          "languagetip": "Please select language",
          "charsettip": "Please select charset",
          "coderequired": "Code is required",
          "successtip": "Add language {0} success"
        },
        "customcontext": {
          "namerequired": 'Context name is required.',
          "labeltip": 'Please select label(s)'
        }
      },
      browse: '上传字典',
      generating: 'Generating...',
      choosefile: '选择文件',
      uploadingfile: '正在上传：',
      uploadfinished: '上传完成。'
    },
    "zh-cn": true
  });

}).call(this);
