// Generated by CoffeeScript 1.6.2
(function() {
  define({
    root: {
      task: {
        open: 'Open',
        closed: 'Closed',
        confirmmsg: 'Do you want to keep the task open?'
      }
    },
    "zh-cn": true
  });

}).call(this);
