// Generated by CoffeeScript 1.4.0
(function() {

  define({
    root: {
      select: {
        languagefilter: {
          title: '请选择要显示的语言',
          'dummy': ''
        }
      },
      msgbox: {
        createtranstask: {
          confirm: 'Do you want to manage the task now?',
          'dummy': ''
        },
        transstatus: {
          msg: 'Change translation status successful.',
          'dummy': ''
        }
      },
      trans: {
        nottranslated: '未翻译',
        inprogress: '翻译中',
        translated: '已翻译'
      }
    },
    "zh-cn": true
  });

}).call(this);
