// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'appmng/dictionary_grid', 'jsfileuploader/jquery.iframe-transport', 'jsfileuploader/jquery.fileupload'], function($, grid) {
    $("#selAppVersion").change(function() {
      return grid.appChanged({
        version: $(this).find("option:selected").text(),
        id: $(this).val()
      });
    });
    $("#progressbar").progressbar();
    $("#dctFileUpload").fileupload({
      type: 'POST',
      url: 'app/deliver-app-dict',
      add: function(e, data) {
        $.each(data.files, function(index, file) {
          return $('#uploadStatus').html("Uploading file: " + file.name);
        });
        return data.submit();
      },
      done: function(e, data) {
        return $.each(data.files, function(index, file) {
          return $('#uploadStatus').html("" + file.name + " upload finished.");
        });
      },
      progressall: function(e, data) {
        console.log("I am in progress.");
        return $('#progressbar').progressbar("value", parseInt(data.loaded / data.total * 100, 10));
      }
    });
    return {
      refresh: function(info) {
        $('#appDispProductName').html(info.parent.text);
        $('#appDispAppName').html(info.text);
        return $.getJSON("rest/applications/apps/" + info.id, {}, function(json) {
          $("#selAppVersion").empty().append($(json).map(function() {
            return new Option(this.version, this.id);
          }));
          return $("#selAppVersion").trigger("change");
        });
      }
    };
  });

}).call(this);
