// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'appmng/dictionary_grid'], function($, grid) {
    console.log("application panel initlized");
    $("#selAppVersion").change(function() {
      return console.log("dictionary update");
    });
    return {
      refresh: function(info) {
        console.log(info);
        $('#appDispProductName').html(info.parent.text);
        $('#appDispAppName').html(info.text);
        return $.getJSON("rest/applications/apps/" + info.id, {}, function(json) {
          $("#selAppVersion").empty().append($(json).map(function() {
            return new Option(this.version, this.id);
          }));
          return $("#selAppVersion").trigger("change");
        });
      }
    };
  });

}).call(this);
