// Generated by CoffeeScript 1.3.3
(function() {

  define(['jqtree', 'appmng/dialogs', 'appmng/layout', 'appmng/product_panel', 'appmng/application_panel'], function($, dialogs, layout, productpnl, apppnl) {
    var URL, ids;
    ids = {
      navigateTree: 'appTree'
    };
    URL = {
      navigateTree: 'rest/products?nocache=' + new Date().getTime()
    };
    $.getJSON(URL.navigateTree, {}, function(treeInfo) {
      var _this = this;
      $.jstree._themes = "css/jstree/themes/";
      return ($("#" + ids.navigateTree).jstree({
        json_data: {
          data: treeInfo
        },
        ui: {
          select_limit: 1
        },
        themes: {},
        core: {},
        plugins: ["themes", "json_data", "ui", "core"]
      })).bind("select_node.jstree", function(event, node) {
        var appTree, nodeInfo, parent;
        appTree = $.jstree._reference("#" + ids.navigateTree);
        parent = appTree._get_parent(node.rslt.obj);
        nodeInfo = {
          text: appTree.get_text(node.rslt.obj),
          parent: parent,
          id: node.rslt.obj.attr("id")
        };
        if (-1 === nodeInfo.parent) {
          productpnl.refresh(nodeInfo);
          return layout.showProductPanel();
        } else {
          nodeInfo.parent = {
            id: parent.attr('id'),
            text: appTree.get_text(parent)
          };
          apppnl.refresh(nodeInfo);
          return layout.showApplicationPanel();
        }
      });
    });
    return {
      getSelected: function() {
        var appTree, info, parent, selectedNode;
        info = {};
        appTree = $.jstree._reference("#" + ids.navigateTree);
        selectedNode = appTree.get_selected();
        info.id = selectedNode.attr("id");
        info.text = appTree.get_text(selectedNode);
        parent = appTree._get_parent(selectedNode);
        if (-1 === parent) {
          info.parent = null;
          return info;
        }
        info.parent = {
          id: parent.attr('id'),
          text: appTree.get_text(parent)
        };
        return info;
      }
    };
  });

}).call(this);
