// Generated by CoffeeScript 1.3.3
(function() {

  define(['jqueryui', 'jqmsgbox', 'i18n!nls/common'], function($, msgbox, c18n) {
    var ids, newOrAddApplication, newProduct, newProductRelease,
      _this = this;
    ids = {
      button: {
        new_product: 'newProduct'
      },
      dialog: {
        new_product: 'newProductDialog',
        new_product_release: 'newProductReleaseDialog',
        new_or_add_application: 'newOrAddApplicationDialog'
      },
      productName: '#productName',
      product_duplication: '#dupVersion'
    };
    console.log(c18n.cancel);
    newProduct = $("#" + ids.dialog.new_product).dialog({
      autoOpen: false,
      height: 200,
      width: 400,
      modal: true,
      buttons: [
        {
          text: c18n.ok,
          click: function() {
            $.post('app/create-product', {
              name: $(ids.productName).val()
            }, function(json) {
              if (json.status !== 0) {
                $.msgBox(json.message, null, {
                  title: 'Error',
                  width: 300,
                  height: 'auto'
                });
                return false;
              }
              return (require('appmng/apptree')).addNewProductBase({
                name: $(ids.productName).val(),
                id: json.id
              });
            });
            return $(this).dialog("close");
          }
        }, {
          text: c18n.cancel,
          click: function() {
            return $(this).dialog("close");
          }
        }
      ]
    });
    $("#" + ids.button.new_product).button().click(function(e) {
      return newProduct.dialog("open");
    });
    newProductRelease = $("#" + ids.dialog.new_product_release).dialog({
      autoOpen: false,
      height: 200,
      width: 500,
      modal: true,
      buttons: {
        'OK': function() {
          alert('OK');
          return $(this).dialog("close");
        },
        'Cancel': function() {
          alert('Cancel');
          return $(this).dialog("close");
        }
      },
      open: function(event, ui) {
        return console.log($(exports.product_panel.select_product_version_id)[0]);
      }
    });
    newOrAddApplication = $("#" + ids.dialog.new_or_add_application).dialog({
      autoOpen: false
    });
    return {
      newProduct: newProduct,
      newProductRelease: newProductRelease,
      newOrAddApplication: newOrAddApplication
    };
  });

}).call(this);
