// Generated by CoffeeScript 1.6.2
(function() {
  define(['jqgrid', 'dms-util'], function($, util) {
    var grid, lastEditedCell, pagerId;

    pagerId = "#globalSearchResultGridPager";
    lastEditedCell = null;
    return grid = $('#globalSearchResultGrid').jqGrid({
      url: 'json/dummy.json',
      mtype: 'post',
      datatype: 'local',
      width: 800,
      height: 300,
      pager: pagerId,
      editurl: "",
      rowNum: 40,
      rowList: [20, 40, 80, 160],
      sortorder: 'asc',
      viewrecords: true,
      caption: 'result',
      viewrecords: true,
      gridview: true,
      multiselect: false,
      cellEdit: false,
      colNames: ['Prod', 'Prod ver', 'Application', 'App ver', 'Dictionary', 'Dict ver', 'Label', 'Reference Language', 'Max Length', 'Context', 'T', 'N', 'I'],
      colModel: [
        {
          name: 'prod',
          index: 'app.name',
          width: 50,
          editable: false,
          align: 'left'
        }, {
          name: 'prod.version',
          index: 'app.version',
          width: 50,
          editable: false,
          align: 'left'
        }, {
          name: 'app',
          index: 'app.name',
          width: 50,
          editable: false,
          align: 'left'
        }, {
          name: 'app.version',
          index: 'app.version',
          width: 50,
          editable: false,
          align: 'left'
        }, {
          name: 'dict',
          index: 'dictionary.base.name',
          width: 300,
          editable: false,
          align: 'left'
        }, {
          name: 'dict.version',
          index: 'dictionary.version',
          width: 50,
          editable: false,
          align: 'left'
        }, {
          name: 'key',
          index: 'key',
          width: 100,
          editable: false,
          align: 'left'
        }, {
          name: 'reference',
          index: 'reference',
          width: 300,
          editable: false,
          align: 'left'
        }, {
          name: 'maxlen',
          index: 'maxLength',
          width: 50,
          editable: false,
          align: 'left'
        }, {
          name: 'ctx',
          index: 'context.name',
          width: 100,
          editable: false,
          align: 'left'
        }, {
          name: 't',
          index: 't',
          sortable: true,
          width: 18,
          align: 'right',
          formatter: 'showlink',
          formatoptions: {
            baseLinkUrl: '#',
            addParam: encodeURI("&status=2")
          }
        }, {
          name: 'n',
          index: 'n',
          formatter: 'showlink',
          sortable: true,
          width: 18,
          align: 'right',
          formatoptions: {
            baseLinkUrl: '#',
            addParam: encodeURI("&status=0")
          }
        }, {
          name: 'i',
          index: 'i',
          formatter: 'showlink',
          sortable: true,
          width: 18,
          align: 'right',
          formatoptions: {
            baseLinkUrl: '#',
            addParam: encodeURI("&status=1")
          }
        }
      ],
      gridComplete: function() {
        grid = $(this);
        $('a', this).each(function(index, a) {
          if ('0' === $(a).text()) {
            return $(a).before(' ').remove();
          }
        });
        return $('a', this).css('color', 'blue').click(function() {
          var param, rowData;

          param = util.getUrlParams(this.href);
          rowData = grid.getRowData(param.id);
          param.key = rowData.key;
          param.ref = rowData.reference;
          $('#stringSettingsTranslationDialog').data({
            param: param
          });
          return $('#stringSettingsTranslationDialog').dialog('open');
        });
      }
    }).setGridParam({
      datatype: 'json'
    }).jqGrid('navGrid', pagerId, {
      edit: false,
      add: false,
      del: false,
      search: false,
      view: false
    }).setGroupHeaders({
      useColSpanStyle: true,
      groupHeaders: [
        {
          startColumnName: "t",
          numberOfColumns: 3,
          titleText: 'Status'
        }
      ]
    });
  });

}).call(this);
