// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var $, langSettingGrid, lastEditedCell;
    $ = require('jqgrid');
    lastEditedCell = null;
    langSettingGrid = $('#languageSettingGrid').jqGrid({
      url: 'json/dummy.json',
      mtype: 'post',
      datatype: 'json',
      width: 500,
      height: 230,
      pager: '#langSettingPager',
      editurl: "",
      rowNum: 10,
      rowList: [10, 20, 30],
      sortname: 'language.name',
      sortorder: 'asc',
      viewrecords: true,
      gridview: true,
      multiselect: true,
      cellEdit: true,
      cellurl: 'app/update-dict-language',
      colNames: ['Code', 'Language', 'Charset'],
      colModel: [
        {
          name: 'code',
          index: 'languageCode',
          width: 40,
          editable: false,
          align: 'left'
        }, {
          name: 'languageId',
          index: 'language.name',
          width: 50,
          editable: true,
          classes: 'editable-column',
          edittype: 'select',
          align: 'left'
        }, {
          name: 'charsetId',
          index: 'charset.name',
          width: 40,
          editable: true,
          classes: 'editable-column',
          edittype: 'select',
          align: 'left'
        }
      ],
      afterEditCell: function(rowid, cellname, val, iRow, iCol) {
        return lastEditedCell = {
          iRow: iRow,
          iCol: iCol,
          name: name,
          val: val
        };
      },
      gridComplete: function() {}
    });
    langSettingGrid.jqGrid('navGrid', '#langSettingPager', {
      edit: false,
      add: false,
      del: true,
      search: false
    }, {}, {
      zIndex: 2000,
      modal: true,
      url: 'app/add-dict-language',
      onclickSubmit: function(params, posdata) {
        return {
          dicts: $('#languageSettingGrid').getGridParam('postData').dict
        };
      },
      onClose: function() {
        return $('#languageSettingGrid').setColProp('code', {
          editable: false
        });
      },
      beforeInitData: function() {
        return $('#languageSettingGrid').setColProp('code', {
          editable: true
        });
      },
      afterSubmit: function(response, postdata) {
        var jsonfromServer;
        jsonfromServer = eval("(" + response.responseText + ")");
        return [jsonfromServer.status === 0, jsonfromServer.message, -1];
      }
    }, {
      zIndex: 2000,
      url: 'app/remove-dict-language'
    });
    langSettingGrid.navButtonAdd('#langSettingPager', {
      caption: "",
      buttonicon: "ui-icon-plus",
      position: "first",
      onClickButton: function() {
        $('#addLanguageDialog').data('param', {
          dicts: [$('#languageSettingGrid').getGridParam('postData').dict]
        });
        return $('#addLanguageDialog').dialog("open");
      }
    });
    $.getJSON('rest/languages', {
      prop: 'id,name'
    }, function(languages) {
      return langSettingGrid.setColProp('languageId', {
        editoptions: {
          value: ($(languages).map(function() {
            return "" + this.id + ":" + this.name;
          })).get().join(';')
        }
      });
    });
    $.getJSON('rest/charsets', {
      prop: 'id,name'
    }, function(charsets) {
      return langSettingGrid.setColProp('charsetId', {
        editoptions: {
          value: ($(charsets).map(function() {
            return "" + this.id + ":" + this.name;
          })).get().join(';')
        }
      });
    });
    return {
      saveLastEditedCell: function() {
        if (lastEditedCell) {
          return langSettingGrid.saveCell(lastEditedCell.iRow, lastEditedCell.iCol);
        }
      }
    };
  });

}).call(this);
