// Generated by CoffeeScript 1.3.3
(function() {
  var dmsPanels, pageLayout, showCenterPanel;

  pageLayout = $("#" + ids.container.page).layout({
    resizable: true,
    closable: true
  });

  dmsPanels = $("#" + ids.container.center).children("div[id^=" + PANEL_PREFIX + "]");

  dmsPanels.addClass("ui-layout-content ui-corner-bottom");

  dmsPanels.css({
    paddingBottom: '1em',
    borderTop: 0
  });

  showCenterPanel = function(panelId) {
    return dmsPanels.each(function(index, panel) {
      if (panel.id === panelId) {
        return $(panel).show();
      } else {
        return $(panel).hide();
      }
    });
  };

  showCenterPanel(ids.welcome);

  exports.layout.showCenterPanel = showCenterPanel;

}).call(this);
