// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var $, langSettingGrid;
    $ = require('jqgrid');
    langSettingGrid = $('#previewLanguageSettingGrid').jqGrid({
      url: '',
      mtype: 'post',
      datatype: 'json',
      width: 500,
      height: 230,
      pager: '#previewLangSettingPager',
      editurl: "",
      rowNum: 100,
      sortname: 'language.name',
      sortorder: 'asc',
      viewrecords: true,
      gridview: true,
      cellEdit: true,
      cellurl: '/app/deliver-update-dict-language',
      colNames: ['Code', 'Language', 'Charset'],
      colModel: [
        {
          name: 'code',
          index: 'languageCode',
          width: 40,
          editable: false,
          align: 'center'
        }, {
          name: 'languageId',
          index: 'language.name',
          width: 50,
          editable: true,
          edittype: 'select',
          align: 'left'
        }, {
          name: 'charsetId',
          index: 'charset.name',
          width: 40,
          editable: true,
          edittype: 'select',
          align: 'center'
        }
      ],
      beforeSubmitCell: function(rowid, cellname, value, iRow, iCol) {
        var postData;
        postData = $(this).getGridParam('postData');
        return {
          dict: postData.dict,
          handler: postData.handler
        };
      },
      afterSubmit: function(response, postdata) {
        var jsonfromServer;
        jsonfromServer = eval("(" + response.responseText + ")");
        return [jsonfromServer.status === 0, jsonfromServer.message, -1];
      }
    });
    langSettingGrid.jqGrid('navGrid', '#previewLangSettingPager', {
      edit: false,
      add: false,
      del: false,
      search: false
    }, {}, {});
    $.getJSON('/rest/languages', {
      prop: 'id,name'
    }, function(languages) {
      return langSettingGrid.setColProp('languageId', {
        editoptions: {
          value: ($(languages).map(function() {
            return "" + this.id + ":" + this.name;
          })).get().join(';')
        }
      });
    });
    return $.getJSON('/rest/charsets', {
      prop: 'id,name'
    }, function(charsets) {
      return langSettingGrid.setColProp('charsetId', {
        editoptions: {
          value: ($(charsets).map(function() {
            return "" + this.id + ":" + this.name;
          })).get().join(';')
        }
      });
    });
  });

}).call(this);
