// Generated by CoffeeScript 1.3.3
(function() {
  var localIds, refresh;

  localIds = {
    select_product_version: '#selVersion',
    new_product_version: '#newVersion',
    disp_product_name: '#dispProductName'
  };

  $(localIds.new_product_version).button({
    text: false,
    icons: {
      primary: "ui-icon-plus"
    }
  }).click(function() {
    return $("#" + ids.dialog.new_product_release).dialog("open");
  });

  $("#newApp").button().click(function() {
    return alert("to be implemented.");
  });

  $("#addApp").button().click(function() {
    return alert("to be implemented.");
  });

  $("#removeApp").button().click(function() {
    return alert("to be implemented.");
  });

  $("#download").button().click(function() {
    return alert("Hello, test");
  });

  $(localIds.select_product_version).change(function() {
    var appGridId, appTree, product, productBaseName, url;
    product = {
      version: $(this).find("option:selected").text(),
      id: $(this).val()
    };
    url = URL.get_application_by_product_id + product.id;
    appGridId = "" + exports.application_grid.application_grid_id;
    $(appGridId).jqGrid('setGridParam', {
      url: url,
      datatype: "json"
    }).trigger("reloadGrid");
    appTree = $.jstree._reference("#" + ids.navigateTree);
    productBaseName = appTree.get_text(appTree.get_selected());
    return $(appGridId).jqGrid('setCaption', "Applications for Product " + productBaseName + " version " + product.version);
  });

  refresh = function(info) {
    $(localIds.disp_product_name).html(info.text);
    return $.getJSON(URL.get_product_by_base_id + info.id, {}, function(json) {
      $(localIds.select_product_version).empty().append($(json).map(function() {
        return new Option(this.version, this.id);
      }));
      return $(localIds.select_product_version).trigger('change');
    });
  };

  exports.product_panel.refresh = refresh;

  exports.product_panel.select_product_version_id = localIds.select_product_version;

}).call(this);
