// Generated by CoffeeScript 1.6.2
(function() {
  define(['hchart'], function($) {
    var colors, options, showChart;

    options = {
      chart: {
        type: 'pie',
        plotBorderWidth: null,
        plotShadow: false
      },
      tooltip: {
        shared: true,
        formatter: function() {
          return "<span style='color:" + this.series.color + "'>" + this.point.name + "</span>: <br/><b>" + this.point.y + "(" + (this.point.percentage.toFixed(2)) + "%)</b><br/>";
        }
      },
      title: {
        text: ''
      },
      legend: {
        align: 'right',
        layout: 'vertical',
        verticalAlign: 'middle',
        width: 100,
        style: 'font-size: 8px'
      },
      plotOptions: {
        pie: {
          showInLegend: true,
          allowPointSelect: true,
          cursor: 'pointer',
          size: '80%',
          dataLabels: {
            enabled: false
          }
        }
      },
      series: [
        {
          name: 'Total translations'
        }
      ]
    };
    colors = Highcharts.getOptions().colors;
    showChart = function(title, json) {
      if (!json) {
        return;
      }
      options.series[0].data = [
        {
          name: 'Duplicated',
          y: json.translationNum - json.distinctTranslationNum
        }, {
          name: 'Distinct',
          y: json.distinctTranslationNum,
          color: colors[3]
        }
      ];
      $('#dupContainer').highcharts(options);
      options.series[0].name = 'Distinct Translations';
      options.series[0].data = [
        ['Translated', json.translatedNum], {
          name: 'Untranslated',
          y: json.untranslatedNum,
          color: colors[3]
        }
      ];
      $('#transContainer').highcharts(options);
      options.series[0].data = [
        ['Auto trans', json.matchedNum], {
          name: 'No match',
          y: json.distinctTranslationNum - json.matchedNum,
          color: colors[3]
        }
      ];
      $('#autoTransContainer').highcharts(options);
      return $("tspan:contains('Highcharts.com')").remove();
    };
    return {
      showChart: showChart
    };
  });

}).call(this);
