// Generated by CoffeeScript 1.6.2
(function() {
  define(['jqueryui', 'i18n!nls/appmng', 'i18n!nls/common', 'dms-util', 'dms-urls', 'appmng/layout', 'appmng/global_search_grid'], function($, i18n, c18n, util, urls, layout, sgrid) {
    var globalSearchInResultPanel, searchActionBtn, searchResultActionBtn, searchText;

    searchText = function(text) {
      var grid, postData;

      grid = $('#globalSearchResultGrid');
      postData = grid.getGridParam('postData');
      postData.format = 'grid';
      postData.text = text;
      postData.prop = 'prod.base.name,prod.version, app.name,app.version, dictionary.base.name, dictionary.version, key,reference,maxLength,context.name,t,n,i';
      delete postData.app;
      delete postData.prod;
      return grid.setCaption(i18n.dialog.searchtext.globalcaption.format(text)).setGridParam({
        url: urls.labels
      }).trigger('reloadGrid');
    };
    searchResultActionBtn = $('#globalSearchInResultPanelAction', '#appmng').attr('title', 'Search').button({
      text: false,
      icons: {
        primary: "ui-icon-search"
      }
    }).height(20).width(20).position({
      my: 'left center',
      at: 'right center',
      of: '#globalSearchInResultPanel'
    });
    searchResultActionBtn.click(function() {
      return searchText($('#globalSearchInResultPanel', '#appmng').val());
    });
    globalSearchInResultPanel = $('#globalSearchInResultPanel', '#appmng').keydown(function(e) {
      if (e.which !== 13) {
        return true;
      }
      searchResultActionBtn.trigger('click');
      return false;
    });
    searchActionBtn = $('#globalSearchAction', '#appmng').attr('title', 'Search').button({
      text: false,
      icons: {
        primary: "ui-icon-search"
      }
    }).height(20).width(20).position({
      my: 'left center',
      at: 'right center',
      of: '#globalSearch'
    }).click(function() {
      var searchValue;

      searchValue = $('#globalSearch', '#appmng').val();
      globalSearchInResultPanel.val(searchValue);
      layout.showSearchPanel();
      return searchText(searchValue);
    });
    $('#globalSearch', '#appmng').keydown(function(e) {
      if (e.which !== 13) {
        return true;
      }
      searchActionBtn.trigger('click');
      return false;
    });
    return $('#goBackToWelcome').button().click(function() {
      return layout.showWelcomePanel();
    });
  });

}).call(this);
