// Generated by CoffeeScript 1.6.2
(function() {
  define(['jqueryui', 'i18n!nls/appmng', 'i18n!nls/common', 'dms-util', 'dms-urls', 'appmng/layout', 'appmng/global_search_grid'], function($, i18n, c18n, util, urls, layout, sgrid) {
    var globalSearchInResultPanel, globalSearchInResultPanelDistinct, searchActionBtn, searchResultActionBtn, searchText;

    searchText = function(text, distinct) {
      var grid, postData;

      if (distinct == null) {
        distinct = false;
      }
      grid = $('#globalSearchResultGrid');
      postData = grid.getGridParam('postData');
      postData.format = 'grid';
      postData.text = text;
      postData.distinct = distinct;
      postData.prop = 'dictionary.base.applicationBase.productBase.name, dictionary.base.applicationBase.name, dictionary.nameVersion, key,reference,maxLength,context.name,t,n,i';
      delete postData.app;
      delete postData.prod;
      return grid.setGridParam({
        url: distinct ? urls.labels_normal : urls.labels
      }).trigger('reloadGrid');
    };
    searchResultActionBtn = $('#globalSearchInResultPanelAction', '#appmng').attr('title', 'Search').button({
      text: false,
      icons: {
        primary: "ui-icon-search"
      }
    }).height(20).width(20).position({
      my: 'left center',
      at: 'right center',
      of: '#globalSearchInResultPanel'
    });
    globalSearchInResultPanelDistinct = $('#globalSearchInResultPanel_distinct');
    searchResultActionBtn.click(function() {
      return searchText($('#globalSearchInResultPanel', '#appmng').val(), Boolean(globalSearchInResultPanelDistinct.attr('checked')));
    });
    globalSearchInResultPanel = $('#globalSearchInResultPanel', '#appmng').keydown(function(e) {
      if (e.which !== 13) {
        return true;
      }
      searchResultActionBtn.trigger('click');
      return false;
    });
    searchActionBtn = $('#globalSearchAction', '#appmng').attr('title', 'Search').button({
      text: false,
      icons: {
        primary: "ui-icon-search"
      }
    }).height(20).width(20).position({
      my: 'left center',
      at: 'right center',
      of: '#globalSearch'
    }).click(function() {
      var distinct, searchValue;

      searchValue = $('#globalSearch', '#appmng').val();
      distinct = Boolean($('#globalSearch_distinct').attr('checked'));
      globalSearchInResultPanel.val(searchValue);
      globalSearchInResultPanelDistinct.attr('checked', distinct);
      layout.showSearchPanel();
      return searchText(searchValue, distinct);
    });
    $('#globalSearch', '#appmng').keydown(function(e) {
      if (e.which !== 13) {
        return true;
      }
      searchActionBtn.trigger('click');
      return false;
    });
    $('#goBackToWelcome').button().click(function() {
      return layout.showWelcomePanel();
    });
    return $('#groupingToggle').button().click(function() {
      var grid;

      grid = $('#globalSearchResultGrid');
      return $("[id^='globalSearchResultGridghead_2_']").each(function(index, elem) {
        grid.groupingToggle(elem.id);
        return true;
      });
    });
  });

}).call(this);
