// Generated by CoffeeScript 1.3.3
(function() {

  define(['jqgrid', 'require'], function($, require) {
    var dicGrid, lastEditedCell;
    lastEditedCell = null;
    dicGrid = $('#stringSettingsGrid').jqGrid({
      url: 'json/dummy.json',
      mtype: 'post',
      datatype: 'local',
      width: $(window).innerWidth() * 0.8,
      height: 300,
      pager: '#stringSettingsPager',
      editurl: "",
      rowNum: 10,
      rowList: [10, 20, 30],
      sortname: 'key',
      sortorder: 'asc',
      viewrecords: true,
      gridview: true,
      multiselect: true,
      cellEdit: true,
      cellurl: 'app/update-label',
      colNames: ['Label', 'Reference Language', 'Max Length', 'Context', 'Description', 'T', 'N', 'I'],
      colModel: [
        {
          name: 'key',
          index: 'key',
          width: 100,
          editable: false,
          align: 'left'
        }, {
          name: 'reference',
          index: 'reference',
          width: 100,
          editable: false,
          align: 'left'
        }, {
          name: 'maxLength',
          index: 'maxLength',
          width: 40,
          editable: true,
          classes: 'editable-column',
          align: 'right'
        }, {
          name: 'context',
          index: 'context.name',
          editrules: {
            required: true
          },
          width: 80,
          editable: true,
          classes: 'editable-column',
          align: 'left'
        }, {
          name: 'description',
          index: 'description',
          width: 60,
          editable: true,
          classes: 'editable-column',
          align: 'left'
        }, {
          name: 't',
          index: 't',
          sortable: false,
          width: 20,
          align: 'right'
        }, {
          name: 'n',
          index: 'n',
          sortable: false,
          width: 20,
          align: 'right'
        }, {
          name: 'i',
          index: 'i',
          sortable: false,
          width: 20,
          align: 'right'
        }
      ],
      afterEditCell: function(rowid, cellname, val, iRow, iCol) {
        return lastEditedCell = {
          iRow: iRow,
          iCol: iCol,
          name: name,
          val: val
        };
      }
    }).setGridParam({
      datatype: 'json'
    }).jqGrid('navGrid', '#stringSettingsPager', {
      edit: false,
      add: false,
      del: false,
      search: false,
      view: false
    }, {}, {}, {});
    return {
      saveLastEditedCell: function() {
        if (lastEditedCell) {
          return dicGrid.saveCell(lastEditedCell.iRow, lastEditedCell.iCol);
        }
      }
    };
  });

}).call(this);
