// Generated by CoffeeScript 1.5.0
(function() {

  define(function(require) {
    var c18n, dialogs, exportAppOrDicts, grid, i18n, init, ready, util;
    i18n = require('i18n!nls/transmng');
    c18n = require('i18n!nls/common');
    grid = require('transmng/trans_grid');
    dialogs = require('transmng/dialogs');
    util = require('dms-util');
    exportAppOrDicts = function(ftype) {
      var checkboxes, id, languages, type;
      id = $('#productRelease').val();
      if (!id) {
        return;
      }
      id = parseInt(id);
      if (-1 === id) {
        return;
      }
      checkboxes = $("#languageFilterDialog input:checkbox[name='languages']:checked");
      languages = checkboxes.map(function() {
        return this.id;
      }).get().join(',');
      type = $("input:radio[name='viewOption'][checked]").val();
      type = type.slice(0, 4);
      if (type[0] === 'a') {
        type = type.slice(0, 3);
      }
      $("#exportForm input[name='prod']").val(id);
      $("#exportForm input[name='language']").val(languages);
      $("#exportForm input[name='type']").val(type);
      if (ftype) {
        $("#exportForm input[name='type']").val(ftype);
      }
      return $("#exportForm").submit();
    };
    init = function() {
      if (typeof console !== "undefined" && console !== null) {
        console.debug("transmng panel init...");
      }
      $('#productBase').change(function() {
        $('#productRelease').empty();
        if (parseInt($('#productBase').val()) === -1) {
          return false;
        }
        return $.getJSON("rest/products/version", {
          base: $(this).val(),
          prop: 'id,version'
        }, function(json) {
          $('#productRelease').append(util.newOption(c18n.select.release.tip, -1));
          $('#productRelease').append(util.json2Options(json, json[json.length - 1].id));
          return $('#productRelease').trigger("change");
        });
      });
      $('#productRelease').change(function() {
        if (-1 === parseInt(this.value)) {
          return;
        }
        $.ajax({
          url: "rest/languages",
          async: false,
          data: {
            prod: this.value,
            prop: 'id,name'
          },
          dataType: 'json',
          success: function(languages) {
            var langTable;
            langTable = util.generateLanguageTable(languages);
            return $("#languageFilterDialog").empty().append(langTable);
          }
        });
        return dialogs.refreshGrid(false, grid);
      });
      $('#productRelease').trigger('change');
      $("#create").button().attr('privilegeName', util.urlname2Action('task/create-task')).click(function() {
        var info;
        info = grid.getTotalSelectedRowInfo();
        if (!info.rowIds.length) {
          $.msgBox(c18n.selrow.format(c18n[grid.getTableType()]), null, {
            title: c18n.warning
          });
          return;
        }
        return dialogs.taskDialog.dialog("open");
      });
      $('#languageFilter').button().click(function() {
        return dialogs.languageFilterDialog.dialog("open");
      });
      $(':radio[name=viewOption]').change(function() {
        return dialogs.refreshGrid(false, grid);
      });
      $("#exportTranslation").button().attr('privilegeName', util.urlname2Action('trans/export-translation-details')).click(function() {
        var info;
        info = grid.getTotalSelectedRowInfo();
        if (!info.rowIds.length) {
          $.msgBox(c18n.selrow.format(c18n[grid.getTableType()]), null, {
            title: c18n.warning
          });
          return;
        }
        return dialogs.exportTranslationDialog.dialog('open');
      });
      $("#exportExcel").click(function() {
        return exportAppOrDicts('excel');
      });
      return $("#exportPDF").click(function() {
        return exportAppOrDicts('pdf');
      });
    };
    ready = function() {
      var gridParent;
      if (typeof console !== "undefined" && console !== null) {
        console.debug("transmng panel ready...");
      }
      gridParent = $('.transGrid_parent');
      return $('#transGrid').setGridWidth(gridParent.width() - 10).setGridHeight(gridParent.height() - 110);
    };
    init();
    return ready();
  });

}).call(this);
