// Generated by CoffeeScript 1.3.3
(function() {
  var i, _i, _len, _ref;

  _ref = ["aa", "bb", "cc"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    i = _ref[_i];
    console.log(i);
  }

}).call(this);
