// Generated by CoffeeScript 1.3.3
(function() {

  define(['jqgrid', 'util', 'require'], function($, util, require) {
    var grid, transGrid;
    grid = {
      dictionary: {
        colNames: ['ID', 'Application', 'Version', 'Dictionary', 'Version', 'Encoding', 'Format', 'Num of String'],
        colModel: [
          {
            name: 'id',
            index: 'id',
            width: 55,
            align: 'center',
            hidden: true,
            frozen: true
          }, {
            name: 'application',
            index: 'application',
            width: 100,
            editable: true,
            stype: 'select',
            edittype: 'select',
            align: 'center',
            editoptions: {
              value: "All:All;0.00:0.00;12:12.00"
            },
            frozen: true
          }, {
            name: 'appVersion',
            index: 'appVersion',
            width: 90,
            editable: true,
            align: 'center',
            frozen: true
          }, {
            name: 'dictionary',
            index: 'dictionary',
            width: 90,
            editable: true,
            align: 'center',
            frozen: true
          }, {
            name: 'dictVersion',
            index: 'dictVersion',
            width: 90,
            editable: true,
            align: 'center',
            frozen: true
          }, {
            name: 'encoding',
            index: 'encoding',
            width: 90,
            editable: true,
            align: 'center',
            frozen: true
          }, {
            name: 'format',
            index: 'format',
            width: 90,
            editable: true,
            align: 'center',
            frozen: true
          }, {
            name: 'numOfString',
            index: 'NumOfString',
            width: 80,
            align: 'center',
            frozen: true
          }
        ]
      },
      application: {
        colNames: ['Dummy', 'ID', 'Application', 'Version', 'Num of String'],
        colModel: [
          {
            name: 'dummy',
            index: 'dummy',
            width: 55,
            align: 'center',
            hidden: true,
            frozen: true
          }, {
            name: 'id',
            index: 'id',
            width: 55,
            align: 'center',
            hidden: true,
            frozen: true
          }, {
            name: 'application',
            index: 'application',
            width: 100,
            editable: true,
            stype: 'select',
            edittype: 'select',
            align: 'center',
            editoptions: {
              value: "All:All;0.00:0.00;12:12.00"
            },
            frozen: true
          }, {
            name: 'appVersion',
            index: 'appVersion',
            width: 90,
            editable: true,
            align: 'center',
            frozen: true
          }, {
            name: 'numOfString',
            index: 'NumOfString',
            width: 80,
            align: 'center',
            frozen: true
          }
        ]
      }
    };
    transGrid = $("#transGridList").jqGrid({
      url: 'json/taskgrid.json',
      mtype: 'POST',
      postData: {},
      editurl: "",
      datatype: 'json',
      width: $(window).width() * 0.95,
      height: 300,
      shrinkToFit: false,
      rownumbers: true,
      loadonce: false,
      pager: '#taskPager',
      rowNum: 10,
      rowList: [10, 20, 30],
      sortname: 'name',
      sortorder: 'asc',
      viewrecords: true,
      gridview: true,
      multiselect: true,
      multikey: "ctrlKey",
      caption: 'Translation Task List',
      colNames: grid.dictionary.colNames,
      colModel: grid.dictionary.colModel,
      groupHeaders: [],
      afterCreate: function(grid) {
        grid.setGroupHeaders({
          useColSpanStyle: true,
          groupHeaders: grid.getGridParam('groupHeaders')
        });
        grid.filterToolbar({
          stringResult: true,
          searchOnEnter: false
        });
        grid.navGrid('#taskPager', {
          edit: false,
          add: false,
          del: false,
          search: false,
          view: false
        });
        grid.navButtonAdd("#taskPager", {
          caption: "Clear",
          title: "Clear Search",
          buttonicon: 'ui-icon-refresh',
          position: 'first',
          onClickButton: function() {
            return grid[0].clearToolbar();
          }
        });
        return grid.setFrozenColumns();
      }
    });
    transGrid.getGridParam('afterCreate')(transGrid);
    $("#create").button().click(function() {
      return alert("not implemented.");
    });
    return {
      productReleaseChanged: function(param) {
        var eprop, gridParam, isApp, langugaeNames, postData, prop, summary, url;
        summary = ($(param.languages).map(function() {
          var _this;
          _this = this;
          return ($([0, 1, 2]).map(function() {
            return "s(" + _this.id + ")[" + this + "]";
          })).get().join(',');
        })).get().join(',');
        gridParam = transGrid.getGridParam();
        langugaeNames = ($(param.languages).map(function() {
          return this.name;
        })).get();
        isApp = param.level === "app";
        gridParam.colNames = isApp ? grid.application.colNames : grid.dictionary.colNames;
        gridParam.colModel = isApp ? grid.application.colModel : grid.dictionary.colModel;
        eprop = "id,app.base.name,app.version," + (isApp ? '' : 'base.name,version, encoding,format,') + "labelNum,";
        console.log(eprop);
        prop = eprop + summary;
        postData = {
          prod: param.release.id,
          format: 'grid',
          prop: prop
        };
        url = isApp ? '' : 'rest/dict';
        console.log(postData);
        return transGrid.updateTaskLanguage(langugaeNames, 'json/taskgrid.json');
      }
    };
  });

}).call(this);
