/*
SQLyog Ultimate v10.00 Beta1
MySQL - 5.5.25 : Database - dms
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
USE `dms`;

/*Table structure for table `alcatel_language_code` */

DROP TABLE IF EXISTS `alcatel_language_code`;

CREATE TABLE `alcatel_language_code` (
  `CODE` varchar(255) NOT NULL,
  `DEFAULT_CODE` bit(1) DEFAULT NULL,
  `LANGUAGE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`CODE`),
  UNIQUE KEY `LANGUAGE_ID` (`LANGUAGE_ID`),
  KEY `FK18E92E87E5130A46` (`LANGUAGE_ID`),
  CONSTRAINT `FK18E92E87E5130A46` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `language` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `application` */

DROP TABLE IF EXISTS `application`;

CREATE TABLE `application` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `PRODUCT_VERSION_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKDCF7993013205EA7` (`PRODUCT_VERSION_ID`),
  CONSTRAINT `FKDCF7993013205EA7` FOREIGN KEY (`PRODUCT_VERSION_ID`) REFERENCES `product_version` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `charset` */

DROP TABLE IF EXISTS `charset`;

CREATE TABLE `charset` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `NO` int(11) DEFAULT NULL,
  `LANGUAGE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK56D8ED2CE5130A46` (`LANGUAGE_ID`),
  CONSTRAINT `FK56D8ED2CE5130A46` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `language` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `context` */

DROP TABLE IF EXISTS `context`;

CREATE TABLE `context` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `dictionary` */

DROP TABLE IF EXISTS `dictionary`;

CREATE TABLE `dictionary` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `FORMAT` varchar(20) DEFAULT NULL,
  `ENCODING` varchar(20) DEFAULT NULL,
  `PATH` varchar(255) DEFAULT NULL,
  `APPLICATION_ID` bigint(20) NOT NULL,
  `LOCKED` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`),
  KEY `FK378F5C96F32D7CAE` (`APPLICATION_ID`),
  CONSTRAINT `FK378F5C96F32D7CAE` FOREIGN KEY (`APPLICATION_ID`) REFERENCES `application` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `dictionary_language` */

DROP TABLE IF EXISTS `dictionary_language`;

CREATE TABLE `dictionary_language` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DICTIONARY_ID` bigint(20) DEFAULT NULL,
  `LANGUAGE_CODE` varchar(255) DEFAULT NULL,
  `LANGUAGE_ID` bigint(20) NOT NULL,
  `CHARSET_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `LANGUAGE_ID` (`LANGUAGE_ID`),
  UNIQUE KEY `CHARSET_ID` (`CHARSET_ID`),
  KEY `FK34DE20E17892C52E` (`CHARSET_ID`),
  KEY `FK34DE20E14A66686` (`DICTIONARY_ID`),
  KEY `FK34DE20E1E5130A46` (`LANGUAGE_ID`),
  CONSTRAINT `FK34DE20E1E5130A46` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `language` (`ID`),
  CONSTRAINT `FK34DE20E14A66686` FOREIGN KEY (`DICTIONARY_ID`) REFERENCES `dictionary` (`ID`),
  CONSTRAINT `FK34DE20E17892C52E` FOREIGN KEY (`CHARSET_ID`) REFERENCES `charset` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `label` */

DROP TABLE IF EXISTS `label`;

CREATE TABLE `label` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DICTIONARY_ID` bigint(20) DEFAULT NULL,
  `REFERENCE` varchar(255) DEFAULT NULL,
  `LABEL_KEY` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `MAX_LENGTH` varchar(255) DEFAULT NULL,
  `CONTEXT_ID` bigint(20) NOT NULL,
  `TEXT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CONTEXT_ID` (`CONTEXT_ID`),
  UNIQUE KEY `TEXT_ID` (`TEXT_ID`),
  KEY `FK44D86D42C7F464E` (`CONTEXT_ID`),
  KEY `FK44D86D4D2ABE426` (`TEXT_ID`),
  KEY `FK44D86D44A66686` (`DICTIONARY_ID`),
  CONSTRAINT `FK44D86D44A66686` FOREIGN KEY (`DICTIONARY_ID`) REFERENCES `dictionary` (`ID`),
  CONSTRAINT `FK44D86D42C7F464E` FOREIGN KEY (`CONTEXT_ID`) REFERENCES `context` (`ID`),
  CONSTRAINT `FK44D86D4D2ABE426` FOREIGN KEY (`TEXT_ID`) REFERENCES `text` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `language` */

DROP TABLE IF EXISTS `language`;

CREATE TABLE `language` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `ISO_CODE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `product` */

DROP TABLE IF EXISTS `product`;

CREATE TABLE `product` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `product_version` */

DROP TABLE IF EXISTS `product_version`;

CREATE TABLE `product_version` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `PRODUCT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKE52769483980FE4E` (`PRODUCT_ID`),
  CONSTRAINT `FKE52769483980FE4E` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `product` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `text` */

DROP TABLE IF EXISTS `text`;

CREATE TABLE `text` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REFERENCE` varchar(255) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `context` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `context` (`context`),
  KEY `FK273D2D54E4D252` (`context`),
  CONSTRAINT `FK273D2D54E4D252` FOREIGN KEY (`context`) REFERENCES `context` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `translation` */

DROP TABLE IF EXISTS `translation`;

CREATE TABLE `translation` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TRANSLATION` varchar(255) DEFAULT NULL,
  `TEXT_ID` bigint(20) NOT NULL,
  `LANGUAGE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TEXT_ID` (`TEXT_ID`),
  UNIQUE KEY `LANGUAGE_ID` (`LANGUAGE_ID`),
  KEY `FK129D8691D2ABE426` (`TEXT_ID`),
  KEY `FK129D8691E5130A46` (`LANGUAGE_ID`),
  CONSTRAINT `FK129D8691E5130A46` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `language` (`ID`),
  CONSTRAINT `FK129D8691D2ABE426` FOREIGN KEY (`TEXT_ID`) REFERENCES `text` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
